name: coverage-tests_python

on:
  # Permit calling trigger
  workflow_call:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # Double quote for version is needed otherwise 3.10 => 3.1
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        # See the list here: https://github.com/actions/runner-images#available-images
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macos-12, macos-13, macos-14]
        exclude:
          - os: macos-14
            python: "3.8"
          - os: macos-14
            python: "3.9"
          
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.os }}" =~ ^"macos" ]]; then
          brew install llvm
        fi
      shell: bash

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}

    - name: Install gstlearn
      run: |
        python -m pip install --upgrade pip
        python -m pip install gstlearn

    - name: Run the python tests
      run: |
        python tests/py/test_Arguments.py
        python tests/py/test_Assessors.py
        python tests/py/test_Matrix.py
